version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: ''
    labels: []
  # We only use npm in examples, so we don't need to update it often.
  # - package-ecosystem: npm
  #   directory: /examples/federation/gateway/
  #   schedule:
  #     interval: monthly
  #   commit-message:
  #     prefix: ''
  #   labels: []
