name: CI

on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: '0 2 * * *'

env:
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings
  RUST_BACKTRACE: 1

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rustup update stable
      - run: cargo test --all --tests

  codegen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rustup update stable
      - run: tools/gen.sh
      - run: git diff --exit-code

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rustup update stable
      - run: cargo clippy --all --all-features --all-targets

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rustup update stable
      - name: Install prettier
        run: sudo npm install -g prettier
      - name: Install shfmt
        run: |
          GO111MODULE=on go get mvdan.cc/sh/v3/cmd/shfmt
          echo "$HOME/go/bin" >>"$GITHUB_PATH"
      - run: tools/fmt.sh
